# version: '3.9'

services:
  hrms-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app   # Mount current backend folder into /app in container
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - app-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      celery -A ML_models.ai_video_interview.utils.queue_utils.celery_app worker --loglevel=info -P solo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
