# version: '3.9'

services:
  hrms-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app  # bind mount: local code → container
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000

    networks:
      - app-network

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    restart: always
    env_file:
      - .env
    volumes:
      - ./backend:/app  # bind mount: local code → container
    command: >
      celery -A app.celery_app worker --loglevel=info
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
