version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app  # bind mount: local code → container
    command: >
      bash -c "gunicorn -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:8000"
    networks:
      - app-network

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: celery_worker
    restart: always
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app  # bind mount: local code → container
    command: >
      bash -c "celery -A app.celery_app worker --loglevel=info"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
